title: Ben Milligan
description: Great Test Websites (Slogan WIP)
theme: minima
baseurl: "" # the subpath of your site, e.g. /blog
url: ""     # the base hostname & protocol, e.g. https://example.com

# Navigation menu (custom data, used in layout)
nav:
  - title: Study Description
    url: /Description/
  - title: FVS
    url: /FVS/
  - title: Ensembles
    url: /Ensembles/
  - title: Resources
    url: /resources/

# Minima theme customizations
minima:
  skin: auto
  social_links:
    github: benr6991
